### PR TITLE
Include deposits in total assets

### PR DESCRIPTION
**Pull request by joelfak**

### CODE REVIEW

**Comment by bitsofwinter** [comment]
Should deposits really be considered a buy? In my case a deposit is mostly something I use when moving funds between exchanges/wallet, i.e. I do a withdraw from one place and then an identical deposit at another place, there are no trades involved. Your case is likely different, need to figure out what you want to achieve and how it would fit with the rest of the code. :-)

**Comment by joelfak** [comment]
Hm. You may be right. However, in my case I made a bank transfer to the
service from my swedish bank account. But I guess the euros where bought in
my bank, before the transfer, so during the deposit no currency trade was
done.

I guess that means that it should not be considered a buy. It should
however, add to the total amount. So you should maybe handle it like a gift
with price 0.

But then again, how should the "genomsnittliga omkostnadsbeloppet" be
entered for currencies obtained elsewhere? Now that I think more about it I
think the correct way to handle this is to create a csv entry for the sek
-> euro trade performed in my bank. And then deposits and withdrawals
should be ignored, just like you say.

My problem was that the initial buy of euros was not registered and
therefore the program fails, since there were no assets when euros was sold.

**Comment by bitsofwinter** [comment]
Ah, yes, that's exactly how I handled this as well, i.e. add trades also for currency conversions, i.e. SEK->EURO and EURO->SEK, I think that's the most correct way to do it in this case as the fiat currency trades should probably be reported on section C on the K4 as well.

**Comment by joelfak** [comment]
Yes, my fix solved this for my case since I have only one deposit, the
first row, which essentially was a fiat trade. But this is a special case
that happened to work out correctly. We should reject this pull request.

sön 22 apr. 2018 kl 14:01 skrev bitsofwinter <notifications@github.com>:

**Pull request closed without merging**
